"""add phone number

Revision ID: 3bddc41fc483
Revises: b9fafac15f5e
Create Date: 2025-03-07 13:46:55.296637

"""
DATABASE_HOSTNAME = DATABASE_HOSTNAME
DATABASE_PORT = DATABASE_PORT
DATABASE_PASSWORD = DATABASE_PASSWORD
DATABASE_NAME = DATABASE_NAME
DATABASE_USERNAME = DATABASE_USERNAME
SECRET_KEY = SECRET_KEY
ALGORITHM = ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = ACCESS_TOKEN_EXPIRE_MINUTES

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bddc41fc483'
down_revision: Union[str, None] = 'b9fafac15f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
